---

- hosts: nodejs
  roles:
    - nodejs
  vars:
    - nodejs_lts_version: "12.*"
    - nodejs_test_version: "14.*"
    - nodejs_user: nodejs
    - nodejs_user_uid: 1101
    - nodejs_group: nodejs
    - nodejs_group_gid: 1101
    - nodejs_app_directory_repo: /home/user/nfs/share/nodejs
    - nodejs_app_directory_runtime: /home/nodejs/applications
    - nodejs_app_directory_perm: 0750
    ###
    - app_name: 18-Chat-Application-master
    - deploy_app_file: 18-Chat-Application-master.zip
    - app_pid: 0
    - deploy_app_port: 3000
    - deploy_app_protocol: tcp
  tasks:
  - name: stop all app by pm2
    shell: pm2 stop all
    args:
      executable: /bin/bash

  - name: remove pm2 menager by npm
    shell: npm remove pm2@latest -g
    args:
      executable: /bin/bash

  - name: nodejs remove
    package:
      name: nodejs
      state: absent

  - name: remove port 90 from firewalld
    firewalld:
      port: 90/tcp
      permanent: yes
      state: disable

  - name: nodejs tools remove
    package:
      name: npm git
      state: absent
