---
  - name: make sure configuration directory exists
    file:
      path: /etc/vsftpd
      mode: 0777
      owner: root
      group: root
      state: directory

  - name: setting up vsftpd with template file
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf
      owner: root
      group: root
      mode: 0600
      backup: true

  - name: setting up vsftpd with template file
    template:
      src: chroot_users.j2
      dest: /etc/vsftpd/chroot_users
      owner: root
      group: root
      mode: 0600
      backup: true
