---
- hosts: nodejs
  roles:
    - nodejs
  tasks:
  - name: add nodejs user
    user:
      name: "{{ nodejs_user }}"
      uid: "{{ nodejs_user_uid }}"
      state: present

  - name: make directory for nodejs apps
    file:
      path: "{{ nodejs_app_directory_runtime }}"
      mode: "{{ nodejs_app_directory_perm }}"
      state: directory

  - name: nodejs installation
    package:
      name: nodejs
      state: present

  - name: nodejs tools installation
    package:
      name: npm,git,unzip
      state: present

  - name: install pm2 menager by npm
    shell: npm install pm2@latest -g
    args:
      executable: /bin/bash

  - name: pm2 set autostart after reboot
    shell: pm2 startup
    args:
      executable: /bin/bash
