---
# tasks file for mariadb

# instalacja mariadb plabook
# instalacja phpmyadmin (chyba na apaczu to musi byc...) z commonu
# enablowanie z commonu
# konfiguracja bazy danych (hasło roota i coś tam jeszcze)
#
# dodanie db
#
# usunięcie
#
# status db
#
